version: '3'
services:
    # auth-service
    auth-service:
        build:
            context: .
            dockerfile: Dockerfile
        image: muhammadajiputramp98/auth-service:0.0.1
        container_name: auth-service
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: auth-service
            SERVICE_TAGS: dev
        working_dir: /Bracked_Break_Project/school_app/
        networks:
            - school-network
        ports:
            - "8081:8081"
        depends_on: 
            - mysql

    #MySQL Service
    mysql:
        image: mysql:5.7.34
        container_name: mysql
        restart: unless-stopped
        tty: true
        ports:
        - "3306:3306"
        environment:
            MYSQL_DATABASE: auth_service
            MYSQL_ROOT_PASSWORD: '@Landung25061995'
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - dbdata:/var/lib/mysql/
            - ./mysql/my.cnf:/etc/mysql/my.cnf
        networks:
            - school-network

#Docker Networks
networks:
    school-network:
      driver: bridge
  
#Volumes
volumes:
    dbdata:
        driver: local